training_args:
  #trial: trial_6
  #special_name:
  trial: debug
  special_name:
  save_total_limit: 1
  save_steps: 500
  eval_steps: 500
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  logging_steps: 10
  report_to: none
  eval_on_start: false

  lr_scheduler_type: cosine
  lr_scheduler_kwargs:
  learning_rate: 6e-4
  warmup_steps: 500000
  max_grad_norm: 1.0

model_args:
  # model_name_or_path: google-t5/t5-base
  config_name: t5-small
  model_name_or_path: google-t5/t5-small


