standalone benchmark:
  steps: 1
  batch_size: 2
  sequence_length: 128
  number_share: 0.1

forward pass benchmark:
  steps: 1
  batch_size: 2
  sequence_length: 128
  number_share: 0.1

training step benchmark:
  steps: 1
  batch_size: 2
  sequence_length: 128
  number_share: 0.1
