name: Publish to PyPI

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install uv CLI
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Install dependencies
        run: |
          uv lock --no-interaction       # update lockfile (if needed)
          uv sync --no-interaction       # install project deps into venv :contentReference[oaicite:0]{index=0}

      - name: Build package
        run: |
          uv build                       # produces dist/*.tar.gz and *.whl :contentReference[oaicite:1]{index=1}

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          uv publish --username $TWINE_USERNAME --password $TWINE_PASSWORD
